version: '3.0'

expectations:

  population_size: 100000

actions:

  ## #################################### 
  ## preliminaries 
  ## #################################### 

  design:
    run: r:latest analysis/design.R
    outputs:
      moderately_sensitive:
        study_dates_json: output/lib/study_parameters.json
        study_dates_rds: output/lib/study_parameters.rds
        jcvi_groups: output/lib/jcvi_groups.csv
        elig_dates: output/lib/elig_dates.csv
        regions: output/lib/regions.csv
        model_varlist: output/lib/model_varlist.rds
        outcomes: output/lib/outcomes.rds
        subgroups: output/lib/subgroups.rds

  ## #################################### 
  ## study definition 
  ## #################################### 
  ## generate dummy data for study_definition 

  dummy_data:
    run: r:latest analysis/dummy_data.R
    needs:
    - design
    outputs:
      moderately_sensitive:
        dummy_data: analysis/dummy_data.feather

  ## study definition 

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
      --output-format feather
    dummy_data_file: analysis/dummy_data.feather
    needs:
    - design
    - dummy_data
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  ## #################################### 
  ## preprocessing 
  ## #################################### 
  ## process data from study_definition 

  data_input_process:
    run: r:latest analysis/preprocess/data_input_process.R
    needs:
    - design
    - dummy_data
    - generate_study_population
    outputs:
      highly_sensitive:
        data_all: output/data/data_*.rds
      moderately_sensitive:
        data_properties: output/tables/data_*_tabulate.txt

  ## apply eligiblity criteria from boxes a and b 

  data_eligible_ab:
    run: r:latest analysis/preprocess/data_eligible_ab.R
    needs:
    - design
    - data_input_process
    outputs:
      highly_sensitive:
        data_eligible_a: output/data/data_eligible_a.rds
        data_eligible_b: output/data/data_eligible_b.rds
      moderately_sensitive:
        eligibility_count: output/lib/eligibility_count_ab.csv
        group_age_ranges: output/lib/group_age_ranges.csv

  ## #################################### 
  ## second_vax_period 
  ## #################################### 
  ## identify second vaccination time periods 
  ## create dataset for identifying second vaccination time periods 

  data_2nd_vax_dates:
    run: r:latest analysis/second_vax_period/data_2nd_vax_dates.R
    needs:
    - design
    - data_input_process
    - data_eligible_ab
    outputs:
      highly_sensitive:
        data_vax_plot: output/second_vax_period/data/data_vax_plot.rds
        second_vax_period_dates_rds: output/second_vax_period/data/second_vax_period_dates.rds
      moderately_sensitive:
        second_vax_period_dates_txt: output/second_vax_period/tables/second_vax_period_dates.txt

  ## plot second vaccination time periods 

  plot_2nd_vax_dates:
    run: r:latest analysis/second_vax_period/plot_2nd_vax_dates.R
    needs:
    - design
    - data_eligible_ab
    - data_2nd_vax_dates
    outputs:
      moderately_sensitive:
        plots_by_region: output/second_vax_period/images/plot_by_region_*.png

  ## apply eligiblity criteria from boxes c, d and e 

  data_eligible_cde:
    run: r:latest analysis/second_vax_period/data_eligible_cde.R
    needs:
    - design
    - data_input_process
    - data_eligible_ab
    - data_2nd_vax_dates
    outputs:
      highly_sensitive:
        data_eligible_e_vax: output/data/data_eligible_e_vax.rds
        data_eligible_e_unvax: output/data/data_eligible_e_unvax.rds

  ## #################################### 
  ## comparisons 
  ## #################################### 
  ## process comparisons data 

  data_comparisons_process:
    run: r:latest analysis/comparisons/data_comparisons_process.R
    needs:
    - design
    - data_input_process
    - data_2nd_vax_dates
    - data_eligible_cde
    outputs:
      highly_sensitive:
        data_comparisons: output/comparisons/data/data_comparisons_*.rds

  ## process tte data 

  data_tte_process_BNT162b2:
    run: r:latest analysis/comparisons/data_tte_process.R BNT162b2
    needs:
    - design
    - data_input_process
    - data_comparisons_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/tte/data/data_tte_BNT162b2*.rds
        event_counts: output/tte/tables/event_counts_BNT162b2.rds

  data_tte_process_ChAdOx:
    run: r:latest analysis/comparisons/data_tte_process.R ChAdOx
    needs:
    - design
    - data_input_process
    - data_comparisons_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/tte/data/data_tte_ChAdOx*.rds
        event_counts: output/tte/tables/event_counts_ChAdOx.rds

  data_tte_process_both:
    run: r:latest analysis/comparisons/data_tte_process.R both
    needs:
    - design
    - data_input_process
    - data_comparisons_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/tte/data/data_tte_both*.rds
        event_counts: output/tte/tables/event_counts_both.rds

  ## process event counts tables 

  process_event_count_tables_BNT162b2:
    run: r:latest analysis/comparisons/process_event_count_tables.R BNT162b2
    needs:
    - design
    - data_tte_process_BNT162b2
    outputs:
      moderately_sensitive:
        tables_events: output/tte/tables/events_BNT162b2*.csv
        tidy_tables_events: output/tte/tables/tidy_events_BNT162b2*.txt

  process_event_count_tables_ChAdOx:
    run: r:latest analysis/comparisons/process_event_count_tables.R ChAdOx
    needs:
    - design
    - data_tte_process_ChAdOx
    outputs:
      moderately_sensitive:
        tables_events: output/tte/tables/events_ChAdOx*.csv
        tidy_tables_events: output/tte/tables/tidy_events_ChAdOx*.txt

  process_event_count_tables_both:
    run: r:latest analysis/comparisons/process_event_count_tables.R both
    needs:
    - design
    - data_tte_process_both
    outputs:
      moderately_sensitive:
        tables_events: output/tte/tables/events_both*.csv
        tidy_tables_events: output/tte/tables/tidy_events_both*.txt

