version: '3.0'

expectations:

  population_size: 100000

actions:

  ## #################################### 
  ## preliminaries 
  ## #################################### 

  design:
    run: r:latest analysis/design.R
    outputs:
      moderately_sensitive:
        study_dates_json: output/lib/study_parameters.json
        study_dates_rds: output/lib/study_parameters.rds
        jcvi_groups: output/lib/jcvi_groups.csv
        elig_dates: output/lib/elig_dates.csv
        regions: output/lib/regions.csv
        model_varlist: output/lib/model_varlist.rds
        outcomes: output/lib/outcomes.rds

  ## #################################### 
  ## study definition 
  ## #################################### 
  ## generate dummy data for study_definition 

  dummy_data:
    run: r:latest analysis/dummy_data.R
    needs:
    - design
    outputs:
      moderately_sensitive:
        dummy_data: analysis/dummy_data.feather

  ## study definition 

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
      --output-format feather
    dummy_data_file: analysis/dummy_data.feather
    needs:
    - design
    - dummy_data
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  ## #################################### 
  ## preprocessing 
  ## #################################### 
  ## process data from study_definition 

  data_input_process:
    run: r:latest analysis/preprocess/data_input_process.R
    needs:
    - design
    - dummy_data
    - generate_study_population
    outputs:
      highly_sensitive:
        data_covs: output/data/data_covs.rds
        data_vax_dates: output/data/data_*_vax_dates.rds
        data_long_dates: output/data/data_long_*_dates.rds
        data_covid_any: output/data/data_covid_any.rds
      moderately_sensitive:
        data_properties: output/tables/data_processed_tabulate.txt

  ## apply eligiblity criteria from boxes a and b 

  data_eligible_ab:
    run: r:latest analysis/preprocess/data_eligible_ab.R
    needs:
    - design
    - data_input_process
    outputs:
      highly_sensitive:
        data_eligible_a: output/data/data_eligible_a.rds
        data_eligible_b: output/data/data_eligible_b.rds
      moderately_sensitive:
        eligibility_count: output/lib/eligibility_count_ab.csv
        group_age_ranges: output/lib/group_age_ranges.csv

  ## #################################### 
  ## second_vax_period 
  ## #################################### 
  ## identify second vaccination time periods 
  ## create dataset for identifying second vaccination time periods 

  data_2nd_vax_dates:
    run: r:latest analysis/second_vax_period/data_2nd_vax_dates.R
    needs:
    - design
    - data_input_process
    - data_eligible_ab
    outputs:
      highly_sensitive:
        data_vax_plot: output/second_vax_period/data/data_vax_plot.rds
        second_vax_period_dates_rds: output/lib/second_vax_period_dates.rds
      moderately_sensitive:
        second_vax_period_dates_csv: output/lib/second_vax_period_dates.csv

  ## plot second vaccination time periods 

  plot_2nd_vax_dates:
    run: r:latest analysis/second_vax_period/plot_2nd_vax_dates.R
    needs:
    - design
    - data_eligible_ab
    - data_2nd_vax_dates
    outputs:
      moderately_sensitive:
        plots_by_region: output/second_vax_period/images/plot_by_region_*.png

  ## apply eligiblity criteria from boxes c and d 

  data_eligible_cd:
    run: r:latest analysis/second_vax_period/data_eligible_cd.R
    needs:
    - design
    - data_input_process
    - data_eligible_ab
    - data_2nd_vax_dates
    outputs:
      highly_sensitive:
        data_eligible_c: output/data/data_eligible_c.rds
        data_eligible_d: output/data/data_eligible_d.rds

  ## #################################### 
  ## comparisons 
  ## #################################### 
  ## process comparisons data 

  data_comparisons_process:
    run: r:latest analysis/comparisons/data_comparisons_process.R
    needs:
    - design
    - data_input_process
    - data_2nd_vax_dates
    - data_eligible_cd
    outputs:
      highly_sensitive:
        data_comparisons: output/data/data_comparisons_*_*.rds

  ## process outcomes data 

  data_outcomes_process:
    run: r:latest analysis/comparisons/data_outcomes_process.R
    needs:
    - design
    - data_input_process
    - data_comparisons_process
    outputs:
      highly_sensitive:
        data_outcomes: output/data/data_outcomes_*_*.rds

  ## apply models and generate reports 
  ## comparison = BNT162b2, outcome = postest 
  ## process tte data for postest 

  data_tte_process_BNT162b2_postest:
    run: r:latest analysis/comparisons/data_tte_process.R BNT162b2 postest
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_BNT162b2_postest.rds

  ## apply cox model for postest 

  apply_model_cox_BNT162b2_postest:
    run: r:latest analysis/comparisons/apply_model_cox.R BNT162b2 postest
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_BNT162b2_postest
    outputs:
      highly_sensitive:
        modelnumber: output/models/BNT162b2_postest_model*.rds
        model_summary_rds: output/models/BNT162b2_postest_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/BNT162b2_postest_incidence.txt
        model_glance: output/models/BNT162b2_postest_modelcox_glance.csv

  ## comparison = BNT162b2, outcome = covidadmitted 
  ## process tte data for covidadmitted 

  data_tte_process_BNT162b2_covidadmitted:
    run: r:latest analysis/comparisons/data_tte_process.R BNT162b2 covidadmitted
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_BNT162b2_covidadmitted.rds

  ## apply cox model for covidadmitted 

  apply_model_cox_BNT162b2_covidadmitted:
    run: r:latest analysis/comparisons/apply_model_cox.R BNT162b2 covidadmitted
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_BNT162b2_covidadmitted
    outputs:
      highly_sensitive:
        modelnumber: output/models/BNT162b2_covidadmitted_model*.rds
        model_summary_rds: output/models/BNT162b2_covidadmitted_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/BNT162b2_covidadmitted_incidence.txt
        model_glance: output/models/BNT162b2_covidadmitted_modelcox_glance.csv

  ## comparison = BNT162b2, outcome = coviddeath 
  ## process tte data for coviddeath 

  data_tte_process_BNT162b2_coviddeath:
    run: r:latest analysis/comparisons/data_tte_process.R BNT162b2 coviddeath
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_BNT162b2_coviddeath.rds

  ## apply cox model for coviddeath 

  apply_model_cox_BNT162b2_coviddeath:
    run: r:latest analysis/comparisons/apply_model_cox.R BNT162b2 coviddeath
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_BNT162b2_coviddeath
    outputs:
      highly_sensitive:
        modelnumber: output/models/BNT162b2_coviddeath_model*.rds
        model_summary_rds: output/models/BNT162b2_coviddeath_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/BNT162b2_coviddeath_incidence.txt
        model_glance: output/models/BNT162b2_coviddeath_modelcox_glance.csv

  ## comparison = BNT162b2, outcome = death 
  ## process tte data for death 

  data_tte_process_BNT162b2_death:
    run: r:latest analysis/comparisons/data_tte_process.R BNT162b2 death
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_BNT162b2_death.rds

  ## apply cox model for death 

  apply_model_cox_BNT162b2_death:
    run: r:latest analysis/comparisons/apply_model_cox.R BNT162b2 death
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_BNT162b2_death
    outputs:
      highly_sensitive:
        modelnumber: output/models/BNT162b2_death_model*.rds
        model_summary_rds: output/models/BNT162b2_death_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/BNT162b2_death_incidence.txt
        model_glance: output/models/BNT162b2_death_modelcox_glance.csv

  ## plot cox model for all outcomes 

  plot_model_cox_BNT162b2:
    run: r:latest analysis/comparisons/plot_cox.R BNT162b2
    needs:
    - design
    - data_2nd_vax_dates
    - apply_model_cox_BNT162b2_postest
    - apply_model_cox_BNT162b2_covidadmitted
    - apply_model_cox_BNT162b2_coviddeath
    - apply_model_cox_BNT162b2_death
    outputs:
      moderately_sensitive:
        plot: output/images/plot_res_BNT162b2.png

  ## tabulate cox model for all outcomes 

  tables_model_cox_BNT162b2:
    run: r:latest analysis/comparisons/tables_cox.R BNT162b2
    needs:
    - design
    - data_2nd_vax_dates
    - data_tte_process_BNT162b2_postest
    - data_tte_process_BNT162b2_covidadmitted
    - data_tte_process_BNT162b2_coviddeath
    - data_tte_process_BNT162b2_death
    - apply_model_cox_BNT162b2_postest
    - apply_model_cox_BNT162b2_covidadmitted
    - apply_model_cox_BNT162b2_coviddeath
    - apply_model_cox_BNT162b2_death
    outputs:
      moderately_sensitive:
        table_glance: output/tables/BNT162b2_modelcox_glance.txt
        table_coefficients: output/tables/BNT162b2_modelcox_coefficients.txt

  ## comparison = ChAdOx, outcome = postest 
  ## process tte data for postest 

  data_tte_process_ChAdOx_postest:
    run: r:latest analysis/comparisons/data_tte_process.R ChAdOx postest
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_ChAdOx_postest.rds

  ## apply cox model for postest 

  apply_model_cox_ChAdOx_postest:
    run: r:latest analysis/comparisons/apply_model_cox.R ChAdOx postest
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_ChAdOx_postest
    outputs:
      highly_sensitive:
        modelnumber: output/models/ChAdOx_postest_model*.rds
        model_summary_rds: output/models/ChAdOx_postest_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/ChAdOx_postest_incidence.txt
        model_glance: output/models/ChAdOx_postest_modelcox_glance.csv

  ## comparison = ChAdOx, outcome = covidadmitted 
  ## process tte data for covidadmitted 

  data_tte_process_ChAdOx_covidadmitted:
    run: r:latest analysis/comparisons/data_tte_process.R ChAdOx covidadmitted
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_ChAdOx_covidadmitted.rds

  ## apply cox model for covidadmitted 

  apply_model_cox_ChAdOx_covidadmitted:
    run: r:latest analysis/comparisons/apply_model_cox.R ChAdOx covidadmitted
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_ChAdOx_covidadmitted
    outputs:
      highly_sensitive:
        modelnumber: output/models/ChAdOx_covidadmitted_model*.rds
        model_summary_rds: output/models/ChAdOx_covidadmitted_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/ChAdOx_covidadmitted_incidence.txt
        model_glance: output/models/ChAdOx_covidadmitted_modelcox_glance.csv

  ## comparison = ChAdOx, outcome = coviddeath 
  ## process tte data for coviddeath 

  data_tte_process_ChAdOx_coviddeath:
    run: r:latest analysis/comparisons/data_tte_process.R ChAdOx coviddeath
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_ChAdOx_coviddeath.rds

  ## apply cox model for coviddeath 

  apply_model_cox_ChAdOx_coviddeath:
    run: r:latest analysis/comparisons/apply_model_cox.R ChAdOx coviddeath
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_ChAdOx_coviddeath
    outputs:
      highly_sensitive:
        modelnumber: output/models/ChAdOx_coviddeath_model*.rds
        model_summary_rds: output/models/ChAdOx_coviddeath_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/ChAdOx_coviddeath_incidence.txt
        model_glance: output/models/ChAdOx_coviddeath_modelcox_glance.csv

  ## comparison = ChAdOx, outcome = death 
  ## process tte data for death 

  data_tte_process_ChAdOx_death:
    run: r:latest analysis/comparisons/data_tte_process.R ChAdOx death
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_ChAdOx_death.rds

  ## apply cox model for death 

  apply_model_cox_ChAdOx_death:
    run: r:latest analysis/comparisons/apply_model_cox.R ChAdOx death
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_ChAdOx_death
    outputs:
      highly_sensitive:
        modelnumber: output/models/ChAdOx_death_model*.rds
        model_summary_rds: output/models/ChAdOx_death_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/ChAdOx_death_incidence.txt
        model_glance: output/models/ChAdOx_death_modelcox_glance.csv

  ## plot cox model for all outcomes 

  plot_model_cox_ChAdOx:
    run: r:latest analysis/comparisons/plot_cox.R ChAdOx
    needs:
    - design
    - data_2nd_vax_dates
    - apply_model_cox_ChAdOx_postest
    - apply_model_cox_ChAdOx_covidadmitted
    - apply_model_cox_ChAdOx_coviddeath
    - apply_model_cox_ChAdOx_death
    outputs:
      moderately_sensitive:
        plot: output/images/plot_res_ChAdOx.png

  ## tabulate cox model for all outcomes 

  tables_model_cox_ChAdOx:
    run: r:latest analysis/comparisons/tables_cox.R ChAdOx
    needs:
    - design
    - data_2nd_vax_dates
    - data_tte_process_ChAdOx_postest
    - data_tte_process_ChAdOx_covidadmitted
    - data_tte_process_ChAdOx_coviddeath
    - data_tte_process_ChAdOx_death
    - apply_model_cox_ChAdOx_postest
    - apply_model_cox_ChAdOx_covidadmitted
    - apply_model_cox_ChAdOx_coviddeath
    - apply_model_cox_ChAdOx_death
    outputs:
      moderately_sensitive:
        table_glance: output/tables/ChAdOx_modelcox_glance.txt
        table_coefficients: output/tables/ChAdOx_modelcox_coefficients.txt

  ## comparison = both, outcome = postest 
  ## process tte data for postest 

  data_tte_process_both_postest:
    run: r:latest analysis/comparisons/data_tte_process.R both postest
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_both_postest.rds

  ## apply cox model for postest 

  apply_model_cox_both_postest:
    run: r:latest analysis/comparisons/apply_model_cox.R both postest
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_both_postest
    outputs:
      highly_sensitive:
        modelnumber: output/models/both_postest_model*.rds
        model_summary_rds: output/models/both_postest_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/both_postest_incidence.txt
        model_glance: output/models/both_postest_modelcox_glance.csv

  ## comparison = both, outcome = covidadmitted 
  ## process tte data for covidadmitted 

  data_tte_process_both_covidadmitted:
    run: r:latest analysis/comparisons/data_tte_process.R both covidadmitted
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_both_covidadmitted.rds

  ## apply cox model for covidadmitted 

  apply_model_cox_both_covidadmitted:
    run: r:latest analysis/comparisons/apply_model_cox.R both covidadmitted
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_both_covidadmitted
    outputs:
      highly_sensitive:
        modelnumber: output/models/both_covidadmitted_model*.rds
        model_summary_rds: output/models/both_covidadmitted_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/both_covidadmitted_incidence.txt
        model_glance: output/models/both_covidadmitted_modelcox_glance.csv

  ## comparison = both, outcome = death 
  ## process tte data for death 

  data_tte_process_both_death:
    run: r:latest analysis/comparisons/data_tte_process.R both death
    needs:
    - data_comparisons_process
    - data_outcomes_process
    outputs:
      highly_sensitive:
        data_tte_brand_outcome: output/data/data_tte_both_death.rds

  ## apply cox model for death 

  apply_model_cox_both_death:
    run: r:latest analysis/comparisons/apply_model_cox.R both death
    needs:
    - design
    - data_comparisons_process
    - data_tte_process_both_death
    outputs:
      highly_sensitive:
        modelnumber: output/models/both_death_model*.rds
        model_summary_rds: output/models/both_death_modelcox_summary.rds
      moderately_sensitive:
        incidence_table: output/tables/both_death_incidence.txt
        model_glance: output/models/both_death_modelcox_glance.csv

  ## plot cox model for all outcomes 

  plot_model_cox_both:
    run: r:latest analysis/comparisons/plot_cox.R both
    needs:
    - design
    - data_2nd_vax_dates
    - apply_model_cox_both_postest
    - apply_model_cox_both_covidadmitted
    - apply_model_cox_both_death
    outputs:
      moderately_sensitive:
        plot: output/images/plot_res_both.png

  ## tabulate cox model for all outcomes 

  tables_model_cox_both:
    run: r:latest analysis/comparisons/tables_cox.R both
    needs:
    - design
    - data_2nd_vax_dates
    - data_tte_process_both_postest
    - data_tte_process_both_covidadmitted
    - data_tte_process_both_death
    - apply_model_cox_both_postest
    - apply_model_cox_both_covidadmitted
    - apply_model_cox_both_death
    outputs:
      moderately_sensitive:
        table_glance: output/tables/both_modelcox_glance.txt
        table_coefficients: output/tables/both_modelcox_coefficients.txt

