version: '3.0'

expectations:

  population_size: 100000

actions:

  ## #################################### 
  ## preliminaries 
  ## #################################### 

  design:
    run: r:latest analysis/design.R
    outputs:
      moderately_sensitive:
        study_dates_json: output/lib/study_parameters.json
        study_dates_rds: output/lib/study_parameters.rds
        jcvi_groups: output/lib/jcvi_groups.csv
        elig_dates: output/lib/elig_dates.csv
        regions: output/lib/regions.csv
        model_varlist: output/lib/model_varlist.rds
        outcomes: output/lib/outcomes.rds

  ## #################################### 
  ## study definition 
  ## #################################### 
  ## generate dummy data for study_definition 

  dummy_data:
    run: r:latest analysis/dummy_data.R
    needs:
    - design
    outputs:
      moderately_sensitive:
        dummy_data: analysis/dummy_data.feather

  ## study definition 

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
      --output-format feather
    dummy_data_file: analysis/dummy_data.feather
    needs:
    - design
    - dummy_data
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  ## #################################### 
  ## preprocessing 
  ## #################################### 
  ## process data from study_definition 

  data_input_process:
    run: r:latest analysis/preprocess/data_input_process.R
    needs:
    - design
    - dummy_data
    - generate_study_population
    outputs:
      highly_sensitive:
        data_covs: output/data/data_covs.rds
        data_vax_dates: output/data/data_*_vax_dates.rds
      moderately_sensitive:
        data_properties: output/tables/data_processed_tabulate.txt

  ## process recurring variables as long data 

  data_long_process:
    run: r:latest analysis/preprocess/data_long_process.R
    needs:
    - design
    - data_input_process
    outputs:
      highly_sensitive:
        data_long_dates: output/data/data_long_*_dates.rds

  ## apply eligiblity criteria from boxes a and b 

  data_eligible_ab:
    run: r:latest analysis/preprocess/data_eligible_ab.R
    needs:
    - design
    - data_input_process
    outputs:
      highly_sensitive:
        data_eligible_a: output/data/data_eligible_a.rds
        data_eligible_b: output/data/data_eligible_b.rds
      moderately_sensitive:
        eligibility_count: output/lib/eligibility_count_ab.csv
        group_age_ranges: output/lib/group_age_ranges.csv

  ## #################################### 
  ## second_vax_period 
  ## #################################### 
  ## identify second vaccination time periods 
  ## create dataset for identifying second vaccination time periods 

  data_2nd_vax_dates:
    run: r:latest analysis/second_vax_period/data_2nd_vax_dates.R
    needs:
    - design
    - data_input_process
    - data_eligible_ab
    outputs:
      highly_sensitive:
        data_vax_plot: output/second_vax_period/data/data_vax_plot.rds
        second_vax_period_dates_rds: output/lib/second_vax_period_dates.rds
      moderately_sensitive:
        second_vax_period_dates_csv: output/lib/second_vax_period_dates.csv

  ## plot second vaccination time periods 

  plot_2nd_vax_dates:
    run: r:latest analysis/second_vax_period/plot_2nd_vax_dates.R
    needs:
    - design
    - data_eligible_ab
    - data_2nd_vax_dates
    outputs:
      moderately_sensitive:
        plots_by_region: output/second_vax_period/images/plot_by_region_*.png

  ## apply eligiblity criteria from boxes c and d 

  data_eligible_cd:
    run: r:latest analysis/second_vax_period/data_eligible_cd.R
    needs:
    - design
    - data_input_process
    - data_eligible_ab
    - data_2nd_vax_dates
    outputs:
      highly_sensitive:
        data_eligible_c: output/data/data_eligible_c.rds
        data_eligible_d: output/data/data_eligible_d.rds

  ## #################################### 
  ## comparisons 
  ## #################################### 
  ## process comparisons data 

  data_comparisons_process:
    run: r:latest analysis/comparisons/data_comparisons_process.R
    needs:
    - design
    - data_input_process
    - data_long_process
    - data_2nd_vax_dates
    - data_eligible_cd
    outputs:
      highly_sensitive:
        data_comparisons: output/data/data_comparisons_*_*.rds

  ## process outcomes data 

  data_outcomes_process:
    run: r:latest analysis/comparisons/data_outcomes_process.R
    needs:
    - design
    - data_input_process
    - data_long_process
    - data_comparisons_process
    outputs:
      highly_sensitive:
        data_outcomes: output/data/data_outcomes_*_*.rds

