version: '3.0'

expectations:
  population_size: 100000

actions:

  ##########################################################################
  #### preliminaries
  ##########################################################################
  # study parameters ----
  design:
    run: r:latest analysis/design.R
    outputs:
      highly_sensitive:
        study_dates_json: output/lib/study_parameters.json
        study_dates_rds: output/lib/study_parameters.rds
        jcvi_groups: output/lib/jcvi_groups.csv
        elig_dates: output/lib/elig_dates.csv
        regions: output/lib/regions.csv

  ##########################################################################
  #### data for eligibility criteria and vaccines
  ##########################################################################
  # generate dummy data for study_definition_vax ----      
  dummy_data_vax:
    run: r:latest analysis/vax/dummy_data_vax.R
    needs: [design]
    outputs:
      highly_sensitive:
        dummy_data_vax: analysis/vax/dummy_data_vax.feather

  # study definition for eligiblity criteria and vaccine data ----  
  generate_study_population_vax:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vax --output-format feather
    dummy_data_file: analysis/vax/dummy_data_vax.feather
    needs: [design, dummy_data_vax]
    outputs:
      highly_sensitive:
        cohort: output/input_vax.feather
        
  # process data from study_definition_vax ----  
  data_vax_process:
    run: r:latest analysis/vax/data_vax_process.R
    needs: [design, dummy_data_vax, generate_study_population_vax]
    outputs:
      highly_sensitive:
        data_eligible_a: output/vax/data/data_eligible_a.rds
        data_eligible_b: output/vax/data/data_eligible_b.rds
        vax_data: output/vax/data/data_*_vax_dates.rds
      moderately_sensitive:
        data_properties: output/vax/data_vax_processed_tabulate.txt
        n_eligible: output/vax/n_eligible.csv

  ##########################################################################
  #### identify second vaccination time periods
  ##########################################################################
  # create dataset for identifying second vaccination time periods ----  
  data_vax_plot:
    run: r:latest analysis/second_vax_period/data_vax_plot.R
    needs: [design, data_vax_process]
    outputs:
      highly_sensitive:
        data_moving_average: output/second_vax_period/data/data_ma.rds
      moderately_sensitive:
        second_vax_period_dates: output/lib/second_vax_period_dates.csv
        start_dates: output/lib/start_dates.csv
        end_dates: output/lib/end_dates.csv

  # identify and plot second vaccination time periods ----  
  plot_2nd_vax_dates:
    run: r:latest analysis/second_vax_period/plot_2nd_vax_dates.R
    needs: [design, data_vax_plot]
    outputs:
      moderately_sensitive:
        plots_by_region: output/second_vax_period/images/plot_by_region_*.png

  ##########################################################################
  #### data for covariates
  ##########################################################################
    # generate dummy data for study_definition_vax ----      
  dummy_data_covs:
    run: r:latest analysis/covs/dummy_data_covs.R
    needs: [design, dummy_data_vax, plot_2nd_vax_dates]
    outputs:
      highly_sensitive:
        dummy_data_vax: analysis/covs/dummy_data_covs.feather

  # study definition for covariates ----  
  generate_study_population_covs:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covs --output-format feather
    dummy_data_file: analysis/covs/dummy_data_covs.feather
    needs: [design, plot_2nd_vax_dates, dummy_data_covs]
    outputs:
      highly_sensitive:
        cohort: output/input_covs.feather
