version: '3.0'

expectations:
  population_size: 10000

actions:

  design:
    run: r:latest analysis/design.R
    outputs:
      highly_sensitive:
        study_dates_json: output/lib/study_dates.json
        study_dates_rds: output/lib/study_dates.rds
        jcvi_groups: output/lib/jcvi_groups.csv
        elig_dates: output/lib/elig_dates.csv

  generate_study_population_vax:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vax --output-format feather
    needs: 
    - design
    outputs:
      highly_sensitive:
        cohort: output/input_vax.feather
        
  data_vax_process:
    run: r:latest analysis/eda_index_dates/data_vax_process.R
    needs:
    - design
    - generate_study_population_vax
    outputs:
      highly_sensitive:
        plot_data: output/eda_index_dates/data/data_2nd_dose.rds
        vax_data: output/data/data_*_vax_dates.rds
      moderately_sensitive:
        data_properties: output/data/data_vax_processed_tabulate.txt

  plot_2nd_vax_dates:
    run: r:latest analysis/eda_index_dates/plot_2nd_vax_dates.R
    needs:
    - design
    - generate_study_population_vax
    - data_vax_process
    outputs:
      moderately_sensitive:
        plots_by_region: output/eda_index_dates/images/plot_by_region_*.png
        plots_all: output/eda_index_dates/images/plot_all_*.png