version: '3.0'

expectations:
  population_size: 10000

actions:

  design:
    run: r:latest analysis/design.R
    outputs:
      highly_sensitive:
        study_dates_json: analysis/lib/study_dates.json
        study_dates_rds: analysis/lib/study_dates.rds
        jcvi_groups: analysis/lib/jcvi_groups.csv
        elig_dates: analysis/lib/elig_dates.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    needs: 
    - design
    outputs:
      highly_sensitive:
        cohort: output/input.csv
        
  eda_2nd_vax_dates:
    run: r:latest analysis/explore_2nd_vax_dates.R
    needs:
    - design
    - generate_study_population
    outputs:
      moderately_sensitive:
        data_properties: output/explore_2nd_vax_dates/data_properties/data_processed_tabulate.png
        plots_eda_2nd_vax_dates: output/explore_2nd_vax_dates/images/second_vax_dates_*.png
