version: '3.0'

expectations:

  population_size: 100000

actions:

  ## #################################### 
  ## preliminaries 
  ## #################################### 

  design:
    run: r:latest analysis/design.R
    outputs:
      moderately_sensitive:
        study_dates_json: output/lib/study_parameters.json
        study_dates_rds: output/lib/study_parameters.rds
        jcvi_groups: output/lib/jcvi_groups.csv
        elig_dates: output/lib/elig_dates.csv
        regions: output/lib/regions.csv
        model_varlist: output/lib/model_varlist.rds
        outcomes: output/lib/outcomes.rds
        subgroups: output/lib/subgroups.rds

  ## #################################### 
  ## study definition 
  ## #################################### 
 

  ## study definition 

  generate_study_population_tests:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tests
      --output-format csv
    needs:
    - design
    outputs:
      highly_sensitive:
        cohort: output/input_tests.csv

 