version: '3.0'

expectations:

  population_size: 100000

actions:

  ## #################################### 
  ## preliminaries 
  ## #################################### 

  design:
    run: r:latest analysis/design.R
    outputs:
      moderately_sensitive:
        study_dates_json: output/lib/study_parameters.json
        study_dates_rds: output/lib/study_parameters.rds
        jcvi_groups: output/lib/jcvi_groups.csv
        elig_dates: output/lib/elig_dates.csv
        regions: output/lib/regions.csv
        model_varlist: output/lib/model_varlist.rds
        outcomes: output/lib/outcomes.rds
        strata_vars: output/lib/strata_vars.rds
        subgroups: output/lib/subgroups.rds

  ## #################################### 
  ## study definition 
  ## #################################### 
  ## generate dummy data for study_definition 

  dummy_data_vax:
    run: r:latest analysis/dummy_data_vax.R
    needs:
    - design
    outputs:
      moderately_sensitive:
        dummy_data: analysis/dummy_data_vax.feather

  ## study definition 

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vax
      --output-format feather
    dummy_data_file: analysis/dummy_data.feather
    needs:
    - design
    - dummy_data_vax
    outputs:
      highly_sensitive:
        cohort: output/input_vax.feather

  ## #################################### 
  ## preprocessing 
  ## #################################### 
  ## process data from study_definition 

  data_input_process:
    run: r:latest analysis/preprocess/data_input_process.R
    needs:
    - design
    - dummy_data_vax
    - generate_study_population
    outputs:
      highly_sensitive:
        data_wide_vax_dates: output/data/data_wide_vax_dates.rds
        data_processed: output/data/data_processed.rds
      moderately_sensitive:
        data_properties: output/tables/data_*_tabulate.txt

  ## apply eligiblity criteria from boxes a and b 

  data_eligible_ab:
    run: r:latest analysis/preprocess/data_eligible_ab.R
    needs:
    - design
    - data_input_process
    outputs:
      highly_sensitive:
        data_eligible_a: output/data/data_eligible_a.rds
        data_eligible_b: output/data/data_eligible_b.rds
      moderately_sensitive:
        eligibility_count: output/tables/eligibility_count_ab.txt
        group_age_ranges: output/lib/group_age_ranges.csv

  ## #################################### 
  ## second_vax_period 
  ## #################################### 
  ## identify second vaccination time periods 
  ## create dataset for identifying second vaccination time periods 

  data_2nd_vax_dates:
    run: r:latest analysis/second_vax_period/data_2nd_vax_dates.R
    needs:
    - design
    - data_input_process
    - data_eligible_ab
    outputs:
      highly_sensitive:
        data_vax_plot: output/second_vax_period/data/data_vax_plot.rds
        second_vax_period_dates_rds: output/second_vax_period/data/second_vax_period_dates.rds
      moderately_sensitive:
        second_vax_period_dates_txt: output/second_vax_period/tables/second_vax_period_dates.txt

  ## plot second vaccination time periods 

  plot_2nd_vax_dates:
    run: r:latest analysis/second_vax_period/plot_2nd_vax_dates.R
    needs:
    - design
    - data_eligible_ab
    - data_2nd_vax_dates
    outputs:
      moderately_sensitive:
        plots_by_region: output/second_vax_period/images/plot_by_region_*.png

  ## apply eligiblity criteria from boxes c, d and e 

  data_eligible_cde:
    run: r:latest analysis/second_vax_period/data_eligible_cde.R
    needs:
    - design
    - data_input_process
    - data_eligible_ab
    - data_2nd_vax_dates
    outputs:
      highly_sensitive:
        data_eligible_e_vax: output/data/data_eligible_e_vax.rds
        data_eligible_e_unvax: output/data/data_eligible_e_unvax.rds
        data_eligible_e: output/data/data_eligible_e.csv

  ## #################################### 
  ## study definition ever and k 
  ## #################################### 
  ## study definition ever 

  generate_ever_data:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ever
      --output-format feather
    needs:
    - design
    - data_eligible_cde
    outputs:
      highly_sensitive:
        cohort: output/input_ever.feather

  ## study definition for period 1 

  generate_input_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_1
      --output-format feather
    needs:
    - design
    - data_eligible_cde
    outputs:
      highly_sensitive:
        cohort: output/input_1.feather

  ## study definition for period 2 

  generate_input_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2
      --output-format feather
    needs:
    - design
    - data_eligible_cde
    outputs:
      highly_sensitive:
        cohort: output/input_2.feather

  ## study definition for period 3 

  generate_input_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_3
      --output-format feather
    needs:
    - design
    - data_eligible_cde
    outputs:
      highly_sensitive:
        cohort: output/input_3.feather

  ## study definition for period 4 

  generate_input_4:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_4
      --output-format feather
    needs:
    - design
    - data_eligible_cde
    outputs:
      highly_sensitive:
        cohort: output/input_4.feather

  ## study definition for period 5 

  generate_input_5:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_5
      --output-format feather
    needs:
    - design
    - data_eligible_cde
    outputs:
      highly_sensitive:
        cohort: output/input_5.feather

  ## study definition for period 6 

  generate_input_6:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_6
      --output-format feather
    needs:
    - design
    - data_eligible_cde
    outputs:
      highly_sensitive:
        cohort: output/input_6.feather

  