---
title: "covariate estimates tables"
author: "Elsie Horne"
date: "23/02/2022"
output: 
  officedown::rdocx_document:
  page_size:
    orient: "portrait"
  page_margins:
    bottom: 1.27
    top: 1.27
    right: 1.27
    left: 1.27
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  include = FALSE,
  # set options for table captions
  tab.cap.pre = "Supplementary Table ",
  tab.cap.sep = ". ",
  tab.topcaption = TRUE,
  tab.cap.fp_text = officer::fp_text_lite(
    font.family = "Times New Roman", 
    font.size = 10, 
    bold = TRUE,
    italic = TRUE
    ),
  # table position
  ft.align = "left"
  
  )
```

```{r}
library(officedown)
library(officer)
library(tidyverse)
library(glue)
library(flextable)
```


```{r}
# set text formatting properties
# fp_text(
#   color = "black",
#   font.size = 10,
#   bold = FALSE,
#   italic = FALSE,
#   underlined = FALSE,
#   font.family = "Time New Roman",
#   cs.family = NULL,
#   eastasia.family = NULL,
#   hansi.family = NULL,
#   vertical.align = "baseline",
#   shading.color = "transparent"
# )
```

```{r}
set_flextable_defaults(
  font.family = "Times New Roman",
  font.size = 8,
  font.color = "black",
  table.layout = "fixed",
  digits = 1,
  theme_fun = "theme_box"
  )
```



```{r}
# read estimates data
estimates_all <- readr::read_csv(
  here::here("release20220221", "estimates_all.csv")) %>%
  mutate(across(model, ~as.integer(str_remove(.x, "unadjusted")))) %>%
  filter(variable != "k")

# read varlist
 model_varlist <- readr::read_rds(
    here::here("output", "lib", "model_varlist.rds")
  )
 
# read subgroups
subgroups <- readr::read_rds(
  here::here("output", "lib", "subgroups.rds"))
subgroups_order <- c(4,1,3,2)

# outcomes 
outcomes <- readr::read_rds(
  here::here("output", "lib", "outcomes.rds")
)
outcomes_order <- c(which(outcomes == "covidadmitted"),
                    which(outcomes == "coviddeath"),
                    which(outcomes == "postest"),
                    which(outcomes == "noncoviddeath"),
                    which(outcomes == "anytest"))
select_outcomes <- unname(outcomes[outcomes_order])
```

```{r}
estimates_list <- estimates_all %>%
  mutate(across(subgroup, factor, levels = subgroups_order)) %>%
  group_split(subgroup, comparison) %>%
  as.list()
```

```{r}
create_table <- function(i) {
  subgroup <- subgroups[unique(estimates_list[[i]]$subgroup)]
  comparison <- unique(estimates_list[[i]]$comparison)
  comparison <- if_else(comparison %in% "both", "BNT162b2 vs ChAdOx", comparison)
  
  table <- estimates_list[[i]] %>%
    mutate(across(c(estimate, conf.low, conf.high), ~format(round(.x, digits=2), nsmall=2))) %>%
    transmute(
      outcome = outcome,
      variable = variable,
      label = label,
      value = if_else(
        !reference_row | is.na(reference_row),
        as.character(glue("{estimate} ({conf.low}-{conf.high})")),
        "1.00 (ref)"
      )
    ) %>%
    pivot_wider(
      names_from = outcome,
      values_from = c(value)
    ) %>%
    select(variable, label, starts_with(select_outcomes)) 
  
  age_order <- sort(unique(table$label[str_detect(table$label, "^age")]))
  age_order <- age_order[age_order!="age"]
  
  history_of_vars <- c(
    "chronic_respiratory_disease",
    "chronic_heart_disease", 
    "chronic_liver_disease", 
    "ckd", 
    "chronic_neuro_inc_ld",
    "diabetes",
    "any_immunosuppression", 
    "ld_inc_ds_and_cp", 
    "sev_ment")
  
  tibble(
    Variable = c(age_order, names(c(model_varlist$demographic, model_varlist$clinical))),
    variable = c(age_order, unname(unlist(model_varlist)))
  ) %>%
    full_join(table, by = "variable") %>%
    filter(Variable != "Age") %>% # remove this line after new results released
    select(-variable) %>%
    mutate(across(Variable, ~if_else(str_detect(.x, "^age"), "Age", .x))) %>%
    mutate(label_old = label) %>%
    mutate(across(label, 
                  ~if_else(.x %in% glue("{history_of_vars}TRUE"),
                           Variable,
                           .x))) %>%
    mutate(across(Variable, 
                  ~if_else(label_old %in% glue("{history_of_vars}TRUE"),
                           "History of",
                           .x))) %>%
    mutate(across(label, 
                  ~if_else(str_detect(.x, "TRUE$"),
                           "yes",
                           .x))) %>%
    mutate(across(Variable, 
                  ~if_else(str_detect(.x, "Number of SARS-CoV-2 tests"),
                           "Number of SARS-CoV-2 tests",
                           .x))) %>%
    mutate(across(all_of(select_outcomes), ~if_else(is.na(.x), "NA", .x))) %>%
    select(-label_old) %>%
    select(Variable, Category = label, all_of(outcomes[outcomes_order])) %>%
    flextable() %>% 
    merge_v(j = "Variable") %>% 
    valign(valign = "top") %>% 
    width(j = 1:7, width = 26/7, unit = "cm") %>%
    # font(fontname = "Times New Roman", part="all") %>%
    # fontsize(size=8, part="all") %>%
    bold(part="header") %>%
    footnote(
      i = 1, j = 2,
      value = as_paragraph(c("Some categories are merged.")),
      ref_symbols = c("a"),
      part = "header", 
      inline = TRUE
      ) %>%
    footnote(
      i = 1, j = 1,
      value = as_paragraph(c("Details about age vars.")),
      ref_symbols = c("b"),
      part = "body", 
      inline = TRUE
      ) %>%
    set_caption(
      caption = glue("Covariate coefficients for the {comparison} model in {subgroup} across all outcomes."),
      style = "Supplementary Table"
    ) %>%
    theme_box() 
}
```

Test some text.

<!---BLOCK_LANDSCAPE_START--->

```{r, include=TRUE, results="asis"}
for (i in 1:2){#seq_along(estimates_list)) {
  
  flextable_to_rmd(create_table(i))
  
}
```

<!---BLOCK_LANDSCAPE_STOP--->



