---
output: 
  bookdown::pdf_document2:
    includes:
      in_header: preamble.tex
      before_body: preface.tex
    keep_tex: true
    latex_engine: xelatex
    toc: false # defined in preface.tex
fontsize: 10
subparagraph: yes
geometry: margin=2cm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  include = FALSE
  )
```

```{r}
library(tidyverse)
library(flextable)
library(glue)
```

```{r}
# read subgroups
subgroups <- readr::read_rds(
  here::here("output", "lib", "subgroups.rds"))
subgroup_labels <- seq_along(subgroups)
subgroup_order <- c(4,1,3,2)
```

```{r}
set_flextable_defaults(
  font.family = "Times New Roman",
  font.size = 8,
  font.color = "black",
  table.layout = "fixed",
  digits = 1#,
  # theme_fun = "theme_vanilla"
  )
```

# Supplementary Methods

# Supplementary Results

```{r}
table1 <- bind_rows(
  lapply(
    1:4,
    function(x) 
      readr::read_csv(here::here("release20220221", glue("table1_{x}_REDACTED.csv")),
                      show_col_types = FALSE) %>%
      mutate(subgroup = x)
    ) 
  ) %>%
  pivot_wider(
    names_from = subgroup,
    values_from = c(BNT162b2, ChAdOx, Unvaccinated),
    names_glue = "{subgroup}_{.value}"
  ) %>%
  select(-`2_ChAdOx`) %>%
  select(Variable, Characteristic, starts_with("4"), starts_with("1"), starts_with("3"), starts_with("2"))

# column names for table
table1_names <- names(table1)
col_names <- str_remove(table1_names, "\\d_")
names(col_names) <- table1_names
cols_subtype <- sapply(
  as.character(subgroup_labels), 
  function(x) sum(str_detect(table1_names, glue("{x}_")))
  )


variable_order_supplement <- c(NA_character_, "Region", "JCVI group", "Resident in long-term residential home",
                               "History of")
table1_ft <- tibble(Variable = variable_order_supplement) %>%
  left_join(table1, by = "Variable") %>%
  group_by(Variable) %>%
  arrange(Characteristic,.by_group = TRUE) %>%
  ungroup() %>%
  as_grouped_data(groups = "Variable") %>%
  as_flextable(hide_grouplabel = TRUE) %>%
  set_header_labels(
    values = as.list(col_names)
  ) %>%
  add_header_row(
    values = c("", subgroups[subgroup_order]),
    colwidths = c(1, cols_subtype[subgroup_order])
  ) %>%
  bold(
    part = "header"
  )
```

\begin{landscape}
```{r table1, include=TRUE, tab.cap="test", tab.cap.pre = "Supplementary Table "}
table1_ft
```
\end{landscape}
